### ISSUE TITLE
Dependency on file existence.

### ISSUE THREAD

**Issue by gautamrege** [amoludage/Email-Extract#1]
Since you have checked in the recipients.csv and the interrupt.txt, it causes some problems
- The interrupt.txt has 19th June. So, the emails get extracted only **after** 19th Jun.
- You have also checked in the recipients.csv file that contains emails from your contacts. I strongly recommend that you remove the contents :)

I tested it out with emptying the contents of these 2 files and it worked really well. Well done.

**Comment by amoludage** [comment]
I have removed that contents from file and pushed  the updated code.
